# Generated by Django 5.1.2 on 2024-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_body_contact_date_created_contact_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(),
        ),
    ]
